  
# 核心任务
- name: ORACLEDATABASE
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
    
  pre_tasks:
    - name: Create dir for as oracle database install_dir
      file: path={{oracledb_work_dir}} recurse=yes state=directory

    - name: Clone role_oracledb to remote 
      git:
       repo: "https://github.com/Websoft9/role_oracledb"
       dest: "{{oracledb_work_dir}}/role_oracledb"
       version: dev

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_cloud, tags: "role_cloud"} 
    - {role: role_jdk, tags: "role_jdk"} 
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
